2020-10-18 04:19:01.249 [error] <0.609.0> CRASH REPORT Process <0.609.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US...">>,...},...}},...},...},...},...},...},...}
2020-10-18 04:19:01.251 [error] <0.609.0> Cowboy stream 1 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.608.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,e...">>,...},...}},...},...},...},...},...}
2020-10-18 04:19:10.913 [error] <0.611.0> CRASH REPORT Process <0.611.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => list_products,message => nil,module => 'Elixir.GetmoreApiChallenge.Getmore',reason => nil},[{'Elixir.GetmoreApiChallenge.Getmore',list_products,[#{}],[]},{'Elixir.GetmoreApiChallengeWeb.ProductController',index,2,[{file,"lib/getmoreApiChallenge_web/controllers/product_controller.ex"},{line,12}]},{'Elixir.GetmoreApiChallengeWeb.ProductController',action,2,[{file,"lib/getmoreApiChallenge_we..."},...]},...]},...},...},...}
2020-10-18 04:19:10.914 [error] <0.611.0> Cowboy stream 2 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.608.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => list_products,message => nil,module => 'Elixir.GetmoreApiChallenge.Getmore',reason => nil},[{'Elixir.GetmoreApiChallenge.Getmore',list_products,[#{}],[]},{'Elixir.GetmoreApiChallengeWeb.ProductController',index,2,[{file,"lib/getmoreApiChallenge_web/controllers/product_controller.ex"},{line,12}]},{'Elixir.GetmoreApiChallengeWeb.ProductController',action,2,[{file,"lib/getmoreApiChallenge_web/..."},...]},...]},...},...}
2020-10-18 04:19:54.076 [error] <0.613.0> CRASH REPORT Process <0.613.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US...">>,...},...}},...},...},...},...},...},...}
2020-10-18 04:19:54.076 [error] <0.613.0> Cowboy stream 3 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.608.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,e...">>,...},...}},...},...},...},...},...}
2020-10-18 04:20:06.899 [error] <0.615.0> CRASH REPORT Process <0.615.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => list_products,message => nil,module => 'Elixir.GetmoreApiChallenge.Getmore',reason => nil},[{'Elixir.GetmoreApiChallenge.Getmore',list_products,[#{}],[]},{'Elixir.GetmoreApiChallengeWeb.ProductController',index,2,[{file,"lib/getmoreApiChallenge_web/controllers/product_controller.ex"},{line,12}]},{'Elixir.GetmoreApiChallengeWeb.ProductController',action,2,[{file,"lib/getmoreApiChallenge_we..."},...]},...]},...},...},...}
2020-10-18 04:20:06.899 [error] <0.615.0> Cowboy stream 4 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.608.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.UndefinedFunctionError',arity => 1,function => list_products,message => nil,module => 'Elixir.GetmoreApiChallenge.Getmore',reason => nil},[{'Elixir.GetmoreApiChallenge.Getmore',list_products,[#{}],[]},{'Elixir.GetmoreApiChallengeWeb.ProductController',index,2,[{file,"lib/getmoreApiChallenge_web/controllers/product_controller.ex"},{line,12}]},{'Elixir.GetmoreApiChallengeWeb.ProductController',action,2,[{file,"lib/getmoreApiChallenge_web/..."},...]},...]},...},...}
2020-10-18 04:20:12.410 [error] <0.617.0> CRASH REPORT Process <0.617.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US...">>,...},...}},...},...},...},...},...},...}
2020-10-18 04:20:12.410 [error] <0.617.0> Cowboy stream 5 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.608.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,e...">>,...},...}},...},...},...},...},...}
2020-10-18 14:43:56.724 [error] <0.406.0>@Elixir.RPX.AMQP.Server:init:11 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([]) at undefined exit with reason no function clause matching 'Elixir.RPX.AMQP.Server':init([]) line 11 in context start_error
2020-10-18 14:44:21.074 [error] <0.546.0>@Elixir.RPX.AMQP.Server:init:11 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([]) at undefined exit with reason no function clause matching 'Elixir.RPX.AMQP.Server':init([]) line 11 in context start_error
2020-10-18 14:47:54.620 [error] <0.406.0>@Elixir.RPX.AMQP.Server:init:11 Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([]) at undefined exit with reason no function clause matching 'Elixir.RPX.AMQP.Server':init([]) line 11 in context start_error
2020-10-18 15:37:35.356 [error] <0.610.0> CRASH REPORT Process <0.610.0> with 0 neighbours exited with reason: {{{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"grafana_session=...">>,...},...}},...},...},...},...},...},...}
2020-10-18 15:37:35.357 [error] <0.610.0> Cowboy stream 2 with ranch listener 'Elixir.GetmoreApiChallengeWeb.Endpoint.HTTP' and connection process <0.607.0> had its request process exit with reason: {{{#{'__exception__' => true,'__struct__' => 'Elixir.Phoenix.Router.NoRouteError',conn => #{'__struct__' => 'Elixir.Plug.Conn',adapter => {'Elixir.Plug.Cowboy.Conn',#{bindings => #{},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"image/avif,image/webp,image/apng,image/*,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"en-US,en;q=0.9">>,<<"connection">> => <<"keep-alive">>,<<"cookie">> => <<"grafana_session=56...">>,...},...}},...},...},...},...},...}
2020-10-18 16:53:00.906 [error] <0.527.0>@Elixir.GetmoreApiChallenge.Getmore:list_products CRASH REPORT Process <0.527.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([])
2020-10-18 16:53:00.906 [error] <0.417.0>@Elixir.GetmoreApiChallenge.Getmore:list_products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.489.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':list_products([]) in context child_terminated
2020-10-18 16:55:30.045 [error] <0.500.0> gen_server <0.500.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2020-10-18 16:55:30.045 [error] <0.500.0> CRASH REPORT Process <0.500.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2020-10-18 16:55:30.045 [error] <0.499.0> Supervisor {<0.499.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:36283 -> 127.0.0.1:5672">>,1}) at <0.500.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2020-10-18 16:55:30.045 [error] <0.499.0> Supervisor {<0.499.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:36283 -> 127.0.0.1:5672">>,1}) at <0.500.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-18 16:55:49.426 [error] <0.548.0>@Elixir.GetmoreApiChallenge.Getmore:/api/products CRASH REPORT Process <0.548.0> with 1 neighbours crashed with reason: call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':'/api/products'([])
2020-10-18 16:55:49.427 [error] <0.417.0>@Elixir.GetmoreApiChallenge.Getmore:/api/products Supervisor 'Elixir.GetmoreApiChallenge.Supervisor' had child 'Elixir.RPX.AMQP.Server' started with 'Elixir.RPX.AMQP.Server':start_link([{worker,'Elixir.GetmoreApiChallenge.Getmore'},{queue_name,<<"products">>}]) at <0.528.0> exit with reason call to undefined function 'Elixir.GetmoreApiChallenge.Getmore':'/api/products'([]) in context child_terminated
2020-10-18 17:00:46.098 [error] <0.553.0> Supervisor {<0.553.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.552.0>, <<"client 127.0.0.1:36093 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
2020-10-18 17:00:46.098 [error] <0.508.0> Supervisor {<0.508.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.507.0>, <<"client 127.0.0.1:36205 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
2020-10-18 17:00:46.098 [error] <0.532.0> Supervisor {<0.532.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.531.0>, <<"client 127.0.0.1:44151 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
