2020-10-31 18:58:37.549 [error] <0.28945.0>@Elixir.GenServer:call CRASH REPORT Process <0.28945.0> with 1 neighbours exited with reason: no such process or port in call to 'Elixir.GenServer':call('Elixir.AMQP.Channel.ReceiverManager', {register_handler,<0.29016.0>,<0.28945.0>,consume,[]}, 5000) in 'Elixir.GenServer':call/3 line 1013
2020-10-31 18:58:53.069 [error] <0.29178.0>@Elixir.Auth:init CRASH REPORT Process <0.29178.0> with 2 neighbours crashed with reason: call to undefined function 'Elixir.Auth':init([])
