2020-10-29 08:25:02.687 [error] <0.333.0> gen_server <0.333.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.687 [error] <0.346.0> gen_server <0.346.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.687 [error] <0.329.0> gen_server <0.329.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.687 [error] <0.342.0> gen_server <0.342.0> terminated with reason: {socket_error,timeout}
2020-10-29 08:25:02.965 [error] <0.329.0> CRASH REPORT Process <0.329.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.965 [error] <0.327.0> Supervisor {<0.327.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.328.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.329.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.965 [error] <0.327.0> Supervisor {<0.327.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.328.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.329.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 08:25:02.965 [error] <0.342.0> CRASH REPORT Process <0.342.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.965 [error] <0.312.0> CRASH REPORT Process <0.312.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.975 [error] <0.310.0> Supervisor {<0.310.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.311.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.312.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.976 [error] <0.310.0> Supervisor {<0.310.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.311.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.312.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 08:25:02.976 [error] <0.340.0> Supervisor {<0.340.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.341.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.342.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.976 [error] <0.340.0> Supervisor {<0.340.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.341.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.342.0> exit with reason reached_max_restart_intensity in context shutdown
2020-10-29 08:25:02.978 [error] <0.355.0> CRASH REPORT Process <0.355.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-10-29 08:25:02.986 [error] <0.353.0> Supervisor {<0.353.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.354.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.355.0> exit with reason {socket_error,timeout} in context child_terminated
2020-10-29 08:25:02.986 [error] <0.353.0> Supervisor {<0.353.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.354.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.355.0> exit with reason reached_max_restart_intensity in context shutdown
